"""
This type stub file was generated by pyright.
"""

"""
MIT License

Copyright (c) 2017-present Devoxin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import typing as t

from .node import Node
from .models import BasePlayer, AudioTrack, DeferredAudioTrack

class Event:
    """The base for all Lavalink events."""

    ...

class TrackStartEvent(Event):
    """This event is emitted when the player starts to play a track."""

    player: BasePlayer
    """The player that started to play a track."""
    track: AudioTrack
    """The track that started playing."""

class TrackStuckEvent(Event):
    """This event is emitted when the currently playing track is stuck. This normally has something to do with the stream you are playing and not Lavalink itself."""

    player: BasePlayer
    """The player that has the playing track being stuck."""
    track: AudioTrack
    """The amount of time the track had while being stuck."""

class TrackExceptionEvent(Event):
    """This event is emitted when an exception occurs while playing a track."""

    player: BasePlayer
    """The player that had the exception occur while playing a track."""
    track: AudioTrack
    """The track that had the exception while playing."""
    exception: str
    """The type of exception that the track had while playing."""
    severity: str
    """The level of severity of the exception."""

class TrackEndEvent(Event):
    """This event is emitted when the player finished playing a track."""

    player: BasePlayer
    """The player that finished playing a track."""
    track: t.Optional[AudioTrack]
    """The track that finished playing.
    
    This could be ``None`` if Lavalink fails to encode the track."""
    reason: str
    """The reason why the track stopped playing."""

class TrackLoadFailedEvent(Event):
    """This is a custom event, emitted when a deferred audio track fails to produce a playable track. The player will not do anything by itself, so it is up to you to skip the broken track."""

    player: BasePlayer
    """The player responsible for playing the track."""
    track: DeferredAudioTrack
    """The track that failed to produce a playable track."""
    original: t.Optional[Exception]
    """The original error, emitted by the track.

    This may be ``None`` if the track did not raise an error, but rather returned ``None`` in place of a playable track."""

class QueueEndEvent(Event):
    """This is a custom event, emitted by the :class:`DefaultPlayer` when
    there are no more tracks in the queue."""

    player: BasePlayer
    """The player that has no more songs in queue."""

class PlayerUpdateEvent(Event):
    """This event is emitted when a player's progress changes."""

    player: BasePlayer
    """The player that's progress was updated."""
    position: int
    """The track's elapsed playback time in milliseconds."""
    timestamp: int
    """The track's elapsed playback time as an epoch timestamp in milliseconds."""
    connected: bool
    """Whether or not the player is connected to the voice gateway."""

class NodeConnectedEvent(Event):
    """This is a custom event, emitted when a connection to a Lavalink node is successfully established."""

    node: Node
    """The node that was successfully connected to."""

class NodeDisconnectedEvent(Event):
    """This is a custom event, emitted when the connection to a Lavalink node drops and becomes unavailable."""

    node: Node
    """The node that was disconnected from."""
    code: t.Optional[int]
    """The status code of the event."""
    reason: t.Optional[str]
    """The reason of why the node was disconnected."""

class NodeChangedEvent(Event):
    """This is a custom event, emitted when a player changes to another Lavalink node.

    Keep in mind this event can be emitted multiple times if a node disconnects and the load balancer moves players to a new node."""

    player: BasePlayer
    """The player whose node was changed."""
    old_node: Node
    """The node the player was moved from."""
    new_node: Node
    """The node the player was moved to."""

class WebSocketClosedEvent(Event):
    """This event is emitted when an audio websocket to Discord is closed. This can happen happen for various reasons, an example being when a channel is deleted.

    Refer to the [Discord Developer docs](https://discord.com/developers/docs/topics/opcodes-and-status-codes#voice-voice-close-event-codes) for a list of close codes and what they mean. This event primarily exists for debug purposes, and no special handling of voice connections should take place unless it is absolutely necessary."""

    player: BasePlayer
    """The player whose audio websocket was closed."""
    code: int
    """The node the player was moved from."""
    reason: str
    """The node the player was moved to."""
    by_remote: bool
    """If the websocket was closed remotely."""
