"""
This type stub file was generated by pyright.
"""

import typing as t

"""
MIT License

Copyright (c) 2017-present Devoxin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

class _NullType:
    pass

_NULL = _NullType()

_T = t.TypeVar('_T')
NullOr = t.Union[_T, _NullType]
BandsType = t.List[t.Tuple[int, float]]
SerializedFilterDataType = t.Dict[t.Any, t.Any]

class Filter:
    # def __init__(self, values: t.Union[t.Dict, t.List, float]) -> None: ...
    # def update(self, **kwargs):
    #     """Updates the internal values to match those provided."""
    #     ...
    def serialize(self) -> SerializedFilterDataType:
        """Transforms the internal values into a dict matching the structure Lavalink expects."""
        ...

class Volume(Filter):
    """
    Adjusts the audio output volume.
    """

    def __init__(self) -> None: ...
    def update(self, volume: float) -> None:
        """
        Modifies the player volume.

        This uses LavaDSP's volume filter, rather than Lavaplayer's native
        volume changer.

        Note
        ----
        The limits are:

            0 ≤ volume ≤ 5

        Parameters
        ----------
        volume: :class:`float`
            The new volume of the player. 1.0 means 100%/default.
        """
        ...
    # def serialize(self) -> dict: ...

class Equalizer(Filter):
    """
    Allows modifying the gain of 15 bands, to boost or reduce the volume of specific frequency ranges.
    For example, this could be used to boost the low (bass) frequencies to act as a 'bass boost'.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        bands: NullOr[BandsType] = ...,
        band: NullOr[int] = ...,
        gain: NullOr[float] = ...,
    ) -> None:
        """
        Modifies the gain of each specified band.

        There are 15 total bands (indexes 0 to 14) that can be modified.

        The meaningful range of each band is -0.25 (muted) to 1.0. A gain of 0.25 doubles the frequency.

        The default gain is 0.0.

        Modifying the gain could alter the volume of output.

        The frequencies of each band are as follows:

        25 Hz, 40 Hz, 63 Hz, 100 Hz, 160 Hz, 250 Hz, 400 Hz, 630 Hz, 1k Hz, 1.6k Hz, 2.5k Hz, 4k Hz, 6.3k Hz, 10k Hz, 16k Hz

        Leftmost frequency represents band 0, rightmost frequency represents band 14.

        Note
        ----
        You can provide either ``bands`` OR ``band`` and ``gain`` for the parameters.

        The limits are:

            0 ≤ band ≤ 14

            -0.25 ≤ gain ≤ 1.0

        Parameters
        ----------
        bands: List[Tuple[:class:`int`, :class:`float`]]
            The bands to modify, and their respective gains.
        band: :class:`int`
            The band to modify.
        gain: :class:`float`
            The new gain of the band.
        """
        ...
    # def serialize(self) -> dict: ...

class Karaoke(Filter):
    """
    Allows for isolating a frequency range (commonly, the vocal range).
    Useful for 'karaoke'/sing-along.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        level: NullOr[float] = ...,
        mono_level: NullOr[float] = ...,
        filter_band: NullOr[float] = ...,
        filter_width: NullOr[float] = ...,
    ) -> None:
        """
        Parameters
        ----------
        level: :class:`float`
            The level of the Karaoke effect.
        mono_level: :class:`float`
            The mono level of the Karaoke effect.
        filter_band: :class:`float`
            The frequency of the band to filter.
        filter_width: :class:`float`
            The width of the filter.
        """
        ...
    # def serialize(self) -> dict: ...

class Timescale(Filter):
    """
    Allows speeding up/slowing down the audio, adjusting the pitch and playback rate.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        speed: NullOr[float] = ...,
        pitch: NullOr[float] = ...,
        rate: NullOr[float] = ...,
    ) -> None:
        """
        Note
        ----
        The limits are:

            0.1 ≤ speed

            0.1 ≤ pitch

            0.1 ≤ rate

        Parameters
        ----------
        speed: :class:`float`
            The playback speed.
        pitch: :class:`float`
            The pitch of the audio.
        rate: :class:`float`
            The playback rate.
        """
        ...
    # def serialize(self) -> dict: ...

class Tremolo(Filter):
    """
    Applies a 'tremble' effect to the audio.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        frequency: NullOr[float] = ...,
        depth: NullOr[float] = ...,
    ) -> None:
        """
        Note
        ----
        The limits are:

            0 < frequency

            0 < depth ≤ 1

        Parameters
        ----------
        frequency: :class:`float`
            How frequently the effect should occur.
        depth: :class:`float`
            The "strength" of the effect.
        """
        ...
    # def serialize(self) -> dict: ...

class Vibrato(Filter):
    """
    Applies a 'wobble' effect to the audio.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        frequency: NullOr[float] = ...,
        depth: NullOr[float] = ...,
    ) -> None:
        """
        Note
        ----
        The limits are:

            0 < frequency ≤ 14

            0 < depth ≤ 1

        Parameters
        ----------
        frequency: :class:`float`
            How frequently the effect should occur.
        depth: :class:`float`
            The "strength" of the effect.
        """
        ...
    # def serialize(self) -> dict: ...

class Rotation(Filter):
    """
    Phases the audio in and out of the left and right channels in an alternating manner.
    This is commonly used to create the 8D effect.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        rotation_hz: float = ...,
    ) -> None:
        """
        Note
        ----
        The limits are:

            0 ≤ rotation_hz

        Parameters
        ----------
        rotation_hz: :class:`float`
            How frequently the effect should occur.
        """
        ...
    # def serialize(self) -> dict: ...

class LowPass(Filter):
    """
    Applies a low-pass effect to the audio, whereby only low frequencies can pass,
    effectively cutting off high frequencies meaning more emphasis is put on lower frequencies.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        smoothing: float = ...,
    ) -> None:
        """
        Note
        ----
        The limits are:

            1 < smoothing

        Parameters
        ----------
        smoothing: :class:`float`
            The strength of the effect.
        """
        ...
    # def serialize(self) -> dict: ...

class ChannelMix(Filter):
    """
    Allows passing the audio from one channel to the other, or isolating individual
    channels.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        left_to_left: NullOr[float] = ...,
        left_to_right: NullOr[float] = ...,
        right_to_left: NullOr[float] = ...,
        right_to_right: NullOr[float] = ...,
    ) -> None:
        """
        Note
        ----
        The limits are:

            0 ≤ leftToLeft ≤ 1.0

            0 ≤ leftToRight ≤ 1.0

            0 ≤ rightToLeft ≤ 1.0

            0 ≤ rightToRight ≤ 1.0

        Parameters
        ----------
        left_to_left: :class:`float`
            The volume level of the audio going from the "Left" channel to the "Left" channel.
        left_to_right: :class:`float`
            The volume level of the audio going from the "Left" channel to the "Right" channel.
        right_to_left: :class:`float`
            The volume level of the audio going from the "Right" channel to the "Left" channel.
        right_to_right: :class:`float`
            The volume level of the audio going from the "Right" channel to the "Left" channel.
        """
        ...
    # def serialize(self) -> dict: ...

class Distortion(Filter):
    """
    As the name suggests, this distorts the audio.
    """

    def __init__(self) -> None: ...
    def update(
        self,
        *,
        sin_offset: NullOr[float] = ...,
        sin_scale: NullOr[float] = ...,
        cos_offset: NullOr[float] = ...,
        cos_scale: NullOr[float] = ...,
        tan_offset: NullOr[float] = ...,
        tan_scale: NullOr[float] = ...,
        offset: NullOr[float] = ...,
        scale: NullOr[float] = ...,
    ) -> None:
        """
        Parameters
        ----------
        sin_offset: :class:`float`
            The sin offset.
        sin_scale: :class:`float`
            The sin scale.
        cos_offset: :class:`float`
            The sin offset.
        cos_scale: :class:`float`
            The sin scale.
        tan_offset: :class:`float`
            The sin offset.
        tan_scale: :class:`float`
            The sin scale.
        offset: :class:`float`
            The sin offset.
        scale: :class:`float`
            The sin scale.
        """
        ...
    # def serialize(self) -> dict: ...
