"""
This type stub file was generated by pyright.
"""

import typing as t

from .stats import Stats
from .models import Plugin, BasePlayer, LoadResult
from .nodemanager import NodeManager

"""
MIT License

Copyright (c) 2017-present Devoxin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

RoutePlannerStatusType = t.Mapping[t.Any, t.Any]

class Node:
    """Represents a Node connection with Lavalink.

    Note
    ----
    Nodes are **NOT** mean't to be added manually, but rather with :func:`Client.add_node`. Doing this can cause invalid cache and much more problems."""

    host: str
    """The address of the Lavalink node."""
    port: int
    """The port to use for websocket and REST connections."""
    password: str
    """The password used for authentication."""
    ssl: bool
    """Whether this node uses SSL (wss/https)."""
    region: str
    """The region to assign this node to."""
    name: str
    """The name the :class:`Node` is identified by."""
    filters: bool
    """Whether or not to use the new ``filters`` op instead of ``equalizer``.
    
    This setting is only used by players."""
    stats: Stats
    """The statistics of how the :class:`Node` is performing."""

    def __init__(
        self,
        manager: NodeManager,
        host: str,
        port: int,
        password: str,
        region: str,
        resume_key: str,
        resume_timeout: int,
        name: str = ...,
        reconnect_attempts: int = ...,
        filters: bool = ...,
        ssl: bool = ...,
    ) -> None: ...
    @property
    def available(self) -> bool:
        """Returns whether the node is available for requests."""
        ...
    @property
    def players(self) -> t.List[BasePlayer]:
        """
        Returns a list of all players on this node.

        Returns
        -------
        List[:class:`BasePlayer`]
        """
        ...
    @property
    def penalty(self) -> int:
        """Returns the load-balancing penalty for this node."""
        ...
    @property
    def http_uri(self) -> str:
        """Returns a 'base' URI pointing to the node's address and port, also factoring in SSL."""
        ...
    async def destroy(self) -> None:
        """|coro|

        Closes the WebSocket connection for this node. No further connection attempts will be made.
        """
        ...
    async def get_tracks(self, query: str, check_local: bool = ...) -> LoadResult:
        """|coro|

        Retrieves a list of results pertaining to the provided query.

        Parameters
        ----------
        query: :class:`str`
            The query to perform a search for.
        check_local: :class:`bool`
            Whether to also search the query on sources registered with this Lavalink client.

        Returns
        -------
        :class:`LoadResult`
        """
        ...
    async def routeplanner_status(self) -> RoutePlannerStatusType:
        """|coro|

        Retrieves the status of the target node's routeplanner.

        Returns
        -------
        :class:`dict`
            A dict representing the routeplanner information.
        """
        ...
    async def routeplanner_free_address(self, address: str) -> bool:
        """|coro|

        Frees up the provided IP address in the target node's routeplanner.

        Parameters
        ----------
        address: :class:`str`
            The address to free.

        Returns
        -------
        :class:`bool`
            True if the address was freed, False otherwise.
        """
        ...
    async def routeplanner_free_all_failing(self) -> bool:
        """|coro|

        Frees up all IP addresses in the target node that have been marked as failing.

        Returns
        -------
        :class:`bool`
            True if all failing addresses were freed, False otherwise.
        """
        ...
    async def get_plugins(self) -> t.List[Plugin]:
        """|coro|

        Retrieves a list of plugins active on this node.

        Returns
        -------
        List[:class:`Plugin`]
            A list of active plugins.
        """
        ...
